/**
 * Year page content from site_map_fix_9.md — unique content per trade/year.
 * Structure: needsToKnowHeading, needsToKnow[], catchOffGuardHeading, catchOffGuard[], howToUseHeading, howToUse[]
 */

export const YEAR_CONTENT_NEW = {};

function add(key, data) {
  YEAR_CONTENT_NEW[key] = data;
}

// --- Electrician Year 1 ---
add('electrician_1', {
  title: 'Electrician Year 1 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: "Preparing for your Year 1 electrician apprenticeship exam? Learn what's on the period exam, what topics to study, and how to pass your first period electrical exam.",
  h1: 'Electrician Apprenticeship — Year 1 Exam Prep',
  intro: "If you are preparing for your first period electrician exam, you are in the right place. Year 1 of the electrical apprenticeship is where the foundation gets built — and the exam reflects that. It covers a broad range of introductory topics, from basic electrical theory to workplace safety to the Canadian Electrical Code. TradeBenchPrep is built on the curriculum so every practice question you see is relevant to what actually appears on your exam.",
  needsToKnowHeading: 'What a Year 1 Electrician Apprentice Needs to Know',
  needsToKnow: [
    { title: "Electrical Theory — Ohm's Law and Basic Circuits", body: "Year 1 exam questions on electrical theory test your ability to apply Ohm's Law (V = IR) to calculate voltage, current, and resistance in series and parallel circuits. You need to be able to work through circuit problems mathematically, not just identify the formula. Know how total resistance is calculated differently in series versus parallel circuits and how current behaves in each. Power calculations (P = VI, P = I²R) also appear consistently." },
    { title: "Workplace Safety — WHMIS, PPE, and Lockout/Tagout", body: "Safety content is heavily weighted in Year 1 and covers WHMIS 2015 labelling and SDS requirements, correct PPE selection for electrical work, and the lockout/tagout procedure step by step. Know the Occupational Health and Safety Act requirements as they apply to electrical trades. Electrical safety specifically — approach distances, arc flash awareness, and working on energized equipment — is always present on the Year 1 exam." },
    { title: 'Tools and Measuring Instruments', body: 'Know the correct name, use, and safe handling of common electrician hand tools — wire strippers, fish tape, conduit benders, knockout punches — and measuring instruments including multimeters, clamp meters, and voltage testers. Questions often describe a task and ask which tool is appropriate, or describe a tool and ask what it measures.' },
    { title: 'Trade Science — Magnetism and Electromagnetism', body: "Year 1 trade science covers the relationship between electricity and magnetism. Know how a magnetic field is produced by current flow, the right-hand rule for conductor and coil polarity, and how electromagnetic induction is the basis for generators and transformers. These concepts appear in introductory form in Year 1 and build into much more detailed content in Years 2 and 3." },
    { title: 'Canadian Electrical Code — Introduction and Navigation', body: "You are not expected to have the CEC memorized in Year 1, but you are expected to be able to navigate it. Know the structure of the code — how rules are numbered, where to find definitions (Section 0), and which sections cover general rules versus specific applications. Practice looking up specific requirements quickly because exam time pressure rewards familiarity with the code layout." },
    { title: 'Conduit and Wiring Methods', body: 'Know the common wiring methods used in residential and light commercial work — NMD90 (Romex), AC90 armoured cable, EMT conduit, and rigid conduit. Understand when each is appropriate, how they are installed, and what the CEC requires for each. Basic conduit bending — 90-degree bends, offsets, and saddle bends — appears in Year 1 content.' },
    { title: 'Blueprint Reading — Basic Electrical Drawings', body: 'Be able to read a basic floor plan with electrical symbols, identify outlet, switch, light fixture, and panel symbols, and understand single-line diagrams. Know how to count circuits from a panel schedule and read a basic electrical legend.' },
  ],
  catchOffGuardHeading: 'Topics Most Likely to Catch You Off Guard',
  catchOffGuard: [
    "Electrical theory calculations are where many apprentices lose marks they should not. The math itself is not complex but working through it accurately under time pressure requires practice. Do not assume you know the calculation until you have worked through it multiple times in quiz conditions.",
    "CEC navigation questions trip up apprentices who have read the code but not practiced finding things in it quickly. The exam does not reward knowing the code exists — it rewards being able to use it efficiently.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 1',
  howToUse: ["Start with Study Mode to go through all possible questions with their explanations — this builds understanding rather than just familiarity. Then use Quiz Mode to test yourself on the areas where you felt least confident. In your final week before the exam, run Full Exam Mode at least twice under timed conditions. Your dashboard tracks your progress automatically every time you return."],
});

// Electrician Year 2
add('electrician_2', {
  title: 'Electrician Year 2 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Study for your Year 2 electrician apprenticeship exam. AC theory, transformers, motors, and motor controls — built on the curriculum.',
  h1: 'Electrician Apprenticeship — Year 2 Exam Prep',
  intro: "Year 2 of the electrician apprenticeship is where the curriculum shifts from DC foundations to AC systems — and the exam difficulty increases accordingly. Alternating current theory, transformers, electric motors, and motor controls are the core of second period content. If you felt comfortable in Year 1, Year 2 will require you to work harder, particularly on the mathematics. TradeBenchPrep gives you structured practice built on the  second period curriculum.",
  needsToKnowHeading: 'What a Year 2 Electrician Apprentice Needs to Know',
  needsToKnow: [
    { title: 'Alternating Current Theory', body: "AC theory is the biggest conceptual jump in Year 2. You need to understand sine waves, frequency, peak versus RMS values, and phase relationships. Capacitors and inductors behave differently in AC circuits than resistors do — know how each affects current, voltage, and phase angle. Power factor, apparent power (VA), true power (W), and reactive power (VAR) form a triangle of relationships that appears consistently on the exam. Calculate power factor and know what it means in practical terms." },
    { title: 'Transformers', body: "Know transformer operating principles — electromagnetic induction, turns ratio, and the relationship between primary and secondary voltage and current. Be able to calculate output voltage, current, and power for single-phase transformers given turns ratio and input values. Three-phase transformer configurations — delta-wye, wye-delta, delta-delta — require you to understand how line and phase voltages relate in each configuration. Transformer nameplate data interpretation is also tested." },
    { title: 'Electric Motors — Construction and Operation', body: "Know the construction of single-phase and three-phase induction motors — stator, rotor, windings, and how the rotating magnetic field is produced. Understand the motor nameplate: voltage, current (FLA), service factor, insulation class, frame size, and RPM. Single-phase motor starting methods — split-phase, capacitor-start, capacitor-run, and shaded pole — each have distinct characteristics and applications you need to know." },
    { title: 'Motor Controls — Starters and Control Circuits', body: "Introduction to magnetic motor starters, contactors, and overload relays. Know the difference between a manual starter and a magnetic starter and when each is used. Be able to read a basic ladder logic control diagram — identify the control circuit components (stop button, start button, holding contact, coil) and trace current flow through the circuit. Understand how overload protection works and how to size overloads for a given motor." },
    { title: 'Canadian Electrical Code — Branch Circuit and Service Calculations', body: "Year 2 CEC content focuses on conductor sizing, overcurrent protection, box fill calculations, and basic load calculations. Be able to determine the correct wire size and breaker size for a given load. Box fill calculation — counting conductors, devices, clamps, and supports to determine minimum box size — appears consistently. Know how to apply demand factors for residential load calculations." },
    { title: 'Residential Wiring — Complete Systems', body: "Know how a complete residential electrical system is put together from the service entrance through the panel to the branch circuits. Understand service entrance equipment, main disconnect, panel bus configuration, and how circuits are protected. GFCI and AFCI requirements under the CEC — where they are required and why — are consistently tested in Year 2." },
    { title: 'Grounding and Bonding', body: "Grounding and bonding is one of the most misunderstood topics in the electrical trade and one of the most consistently tested. Know the difference between grounding (connecting to earth) and bonding (connecting metal parts together). Understand system grounding, equipment grounding, and the specific CEC requirements for grounding conductors sizing and connections." },
  ],
  catchOffGuardHeading: 'What to Focus On First',
  catchOffGuard: [
    "AC mathematics — power factor, apparent power, and transformer calculations — are where the most exam marks are concentrated and where preparation time pays off most. If the math feels uncertain, practice it daily in the two weeks before your exam. Work problems from scratch rather than just reviewing solved examples.",
    "Motor nameplate interpretation is practical knowledge that appears on every Year 2 exam. Know every item on a standard motor nameplate and what it tells you about the motor's application and protection requirements.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 2',
  howToUse: ["Use Study Mode to work through transformer and motor control questions with full explanations before testing yourself. The explanation for each question in Study Mode shows you the reasoning process, which is particularly valuable for multi-step calculation questions. Quiz Mode is most effective for identifying which AC theory topics need more attention. Full Exam Mode builds the timed confidence you need for exam day."],
});

// Electrician Year 3
add('electrician_3', {
  title: 'Electrician Year 3 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Prepare for your Year 3 electrician apprenticeship exam. Commercial wiring, three-phase systems, advanced motor controls, and CEC load calculations. curriculum aligned.',
  h1: 'Electrician Apprenticeship — Year 3 Exam Prep',
  intro: "Year 3 of the electrician apprenticeship moves firmly into commercial and industrial territory. Three-phase power systems, commercial wiring methods, distribution equipment, advanced motor controls, and complex CEC applications define the third period curriculum. The exam is more demanding than previous years and rewards apprentices who have built genuine understanding rather than surface familiarity. TradeBenchPrep is built on the  Year 3 curriculum to give you exactly the practice you need.",
  needsToKnowHeading: 'What a Year 3 Electrician Apprentice Needs to Know',
  needsToKnow: [
    { title: 'Three-Phase Power Systems', body: "Three-phase is the dominant power system in commercial and industrial environments and is heavily tested in Year 3. You need to know wye and delta configurations inside out — how line voltage and phase voltage relate in each (in a wye system, line voltage = phase voltage × √3), how line current and phase current relate in a delta system, and how to calculate three-phase power (P = √3 × VL × IL × PF). Balanced three-phase load calculations appear consistently. Know how to calculate current draw for three-phase motors and other three-phase loads." },
    { title: 'Commercial Wiring Methods', body: "Expand beyond residential wiring methods into the commercial and industrial options — MC cable (metal-clad), tray cable, intermediate metal conduit (IMC), rigid metal conduit (RMC), and wireways. Know the CEC installation requirements for each: support spacing, bending radius, fill calculations, and permitted uses. Conduit fill calculation — determining the maximum number of conductors permitted in a given conduit size — appears on Year 3 exams and requires you to use the CEC fill tables correctly." },
    { title: 'Distribution Equipment', body: "Know panelboards, switchboards, and motor control centres — their construction, ratings, and how they differ in application. Understand how to read a single-line diagram for a commercial distribution system and identify the function of each component. Transformer secondary protection and feeder protection sizing are applied CEC topics at this level." },
    { title: 'Advanced Motor Controls', body: "Year 3 motor controls go significantly beyond the magnetic starter. Know reduced voltage starting methods — autotransformer starters, wye-delta starters, and soft starters — why they are used and how they work. Variable frequency drives (VFDs) — basic operating principle, benefits for motor control and energy efficiency, and common application issues. Reversing motor control circuits — be able to read and interpret a reversing starter control diagram and understand the mechanical and electrical interlocking." },
    { title: 'Hazardous Locations', body: "Hazardous location classification is specific, testable, and often under-studied. Know the Class/Division/Group system: Class I (flammable gases/vapours), Class II (combustible dusts), Class III (ignitable fibres). Know Division 1 versus Division 2 for each class. Understand equipment selection requirements for each classification and why they exist. This is an area where thorough study translates directly into exam marks." },
    { title: 'Commercial Load Calculations', body: "CEC commercial load calculations involve demand factors, connected load versus demand load, and service sizing for commercial occupancies. Be able to work through a complete commercial load calculation following the CEC method — connected loads by category, applicable demand factors, total demand, and resulting service size and conductor requirements." },
    { title: 'Lighting Systems', body: "Commercial lighting systems — fluorescent, HID, LED, and emergency lighting. Know how ballasts work, lamp types and their characteristics, and CEC requirements for emergency lighting including battery backup and testing requirements. Lighting calculation basics — lumens, lux, and footcandles — appear in Year 3 content." },
  ],
  catchOffGuardHeading: 'What Most Apprentices Find Hardest in Year 3',
  catchOffGuard: [
    "Three-phase mathematics consistently separates well-prepared candidates from those who are not. The √3 factor, the difference between line and phase quantities in wye versus delta, and three-phase power calculations are mathematical relationships that require practice to apply accurately under time pressure. Do not just read about them — work through calculation problems repeatedly.",
    "Hazardous location classification rewards apprentices who study it systematically. The Class/Division/Group system is precise and the exam tests specific details. Apprentices who treat it as a secondary topic often regret it.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 3',
  howToUse: ["Three-phase calculation questions in TradeBenchPrep's Quiz Mode are the most effective preparation for the most heavily weighted exam content. Run the Full Exam Mode with timed conditions in your final two weeks — Year 3 is a longer and more complex exam than previous years and time management matters."],
});

// Electrician Year 4
add('electrician_4', {
  title: 'Electrician Year 4 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Study for your Year 4 electrician apprenticeship exam. Industrial power systems, PLCs, power quality, and full CEC mastery. Built on the curriculum.',
  h1: 'Electrician Apprenticeship — Year 4 Exam Prep',
  intro: "Year 4 is the final period of the electrician apprenticeship — the most technically advanced and the broadest in scope. Industrial power systems, programmable logic controllers, power quality, advanced protection systems, and mastery of the Canadian Electrical Code across all occupancy types define the fourth period curriculum. Passing Year 4 qualifies you to challenge the Interprovincial exam for your journeyman electrician certificate. TradeBenchPrep gives you the focused, curriculum-aligned practice you need to finish your apprenticeship strong.",
  needsToKnowHeading: 'What a Year 4 Electrician Apprentice Needs to Know',
  needsToKnow: [
    { title: 'Industrial Power Systems', body: "Industrial power distribution from the utility service entrance through high-voltage switchgear, unit substations, and to the point of use. Know the components of a typical industrial distribution system — primary metering, transformers, switchgear, motor control centres, and branch circuit panels — and how they relate to each other. Understand transformer connections, impedance, and how to size industrial power systems. High-voltage safety — approach distances, PPE requirements, and permit-required work procedures — is consistently tested." },
    { title: 'Programmable Logic Controllers (PLCs)', body: "PLC fundamentals are a Year 4 addition to the curriculum that reflects the modern reality of industrial electrical work. Know PLC architecture — CPU, input/output modules, power supply, and programming terminal. Understand basic ladder logic programming concepts: normally open contacts, normally closed contacts, output coils, and how they relate to relay logic. Be able to trace through a basic PLC ladder logic program and determine outputs given specific input conditions." },
    { title: 'Power Quality', body: "Power quality is increasingly important in modern electrical systems and is tested in Year 4. Know the major power quality issues: harmonics, voltage sags and swells, transients, and flicker. Understand how harmonics are generated (primarily by non-linear loads like VFDs and switching power supplies), how they affect electrical equipment, and how they are mitigated (harmonic filters, isolation transformers, line reactors). Power factor correction — capacitor bank sizing and installation — is also tested at this level." },
    { title: 'Protection Systems and Coordination', body: "Overcurrent protection coordination — ensuring that the correct device operates for a given fault while upstream devices remain closed. Know the time-current characteristics of fuses and circuit breakers and how to read a time-current curve. Ground fault protection for equipment (GFPE) in industrial settings — requirements and operating principles. Arc flash hazard analysis concepts — incident energy, arc flash boundary, and PPE selection — are Year 4 content reflecting current safety standards." },
    { title: 'Renewable Energy Systems', body: "Solar photovoltaic system basics — PV modules, inverters, combiner boxes, and interconnection to the utility grid under the CEC. Know CEC Section 64 requirements for solar PV installations including disconnecting means, conductor sizing, and overcurrent protection. Battery storage system basics and grid interconnection requirements are also covered." },
    { title: 'Canadian Electrical Code — Full Industrial and Special Systems', body: "Year 4 CEC knowledge spans industrial occupancies (Section 20), high voltage installations (Section 36), emergency systems (Section 46), and communication systems (Section 60). Be able to apply the correct code section for any occupancy or system type. Load calculations at the industrial level — demand factors, service entrance sizing, and power factor correction requirements — are applied CEC topics at Year 4." },
    { title: 'Instrumentation and Process Control Basics', body: "4-20mA control loops — what they are, how they work, and how they interface with PLCs and field instruments. Basic instrumentation symbols on P&ID drawings as they relate to electrical installation and termination. Understanding the electrical requirements of instrumentation systems — shielding, grounding, and separation from power wiring." },
  ],
  catchOffGuardHeading: 'What to Prioritize in Year 4 Preparation',
  catchOffGuard: [
    "PLC ladder logic and power quality are Year 4-specific topics where practical job experience varies widely. Apprentices who work in heavy industrial environments may have strong PLC exposure while those in commercial work may have very little. TradeBenchPrep covers both systematically so your exam preparation is complete regardless of your job site experience.",
    "Arc flash and protection coordination concepts are relatively new additions to the electrician curriculum and require dedicated study. These are not intuitive topics — they require reading and practice questions to develop working knowledge.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 4',
  howToUse: ["At Year 4, Full Exam Mode is your most valuable tool. The fourth period exam covers the broadest range of content of any period and timed practice across the full curriculum is the most realistic preparation. Run multiple full exams in your final two to three weeks and use your results to direct remaining study time. Your dashboard will show exactly where your scores are weakest so you can focus efficiently."],
});

// --- Millwright Year 1 ---
add('millwright_1', {
  title: 'Millwright Year 1 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: "Preparing for your Year 1 millwright apprenticeship exam? Learn what the period exam covers — tools, bearings, fasteners, rigging, and safety. Start practicing free.",
  h1: 'Millwright Industrial Mechanic — Year 1 Exam Prep',
  intro: "Year 1 of the millwright apprenticeship covers the mechanical fundamentals that everything else in the trade builds on. Bearings, fasteners, seals, hand tools, rigging, and workplace safety form the core of first period content. The Year 1 exam is broad — it covers a lot of ground — and the apprentices who do best are the ones who have studied systematically rather than relying purely on what they have picked up on the job. TradeBenchPrep is built on the  millwright curriculum to give you exactly that structured preparation.",
  needsToKnowHeading: 'What a Year 1 Millwright Apprentice Needs to Know',
  needsToKnow: [
    { title: "Workplace Safety — The Foundation of Every Year", body: "WHMIS 2015 — labelling requirements, SDS sections and what each contains, and how to respond to hazardous material incidents. Lockout/tagout — know the complete procedure step by step, not just the concept. OHS regulations specific to industrial mechanical work including machine guarding requirements and working around mobile equipment. Safety content is heavily weighted in Year 1 and a question on any safety topic can appear." },
    { title: "Trade Mathematics", body: "Millwright trade math goes beyond basic arithmetic. Know how to convert between imperial and metric units for length, torque, pressure, and force. Understand ratio and proportion as they apply to mechanical advantage, gear ratios, and lever systems. Basic trigonometry — right triangle relationships (SOH-CAH-TOA) — appears in rigging calculations and alignment work. If your math is rusty, sharpen it before your exam — it shows up throughout all four years." },
    { title: "Hand Tools and Measuring Instruments", body: "Know the purpose, correct use, and safe handling of all common millwright hand tools. Torque wrenches — how they work, how to set them, and why torque specifications matter. Precision measuring tools — micrometer, vernier caliper, dial indicator, and feeler gauge — their purpose, how to read them, and their accuracy limits. These are tools a millwright uses daily and the exam assumes you know them well." },
    { title: "Bearings — Types, Installation, and Failure", body: "Bearings are one of the most consistently tested topics across all four years of the millwright apprenticeship. In Year 1 you need to know: rolling element bearing types (ball, cylindrical roller, tapered roller, needle, spherical roller) and their load capacity characteristics. Bearing designation systems — what the numbers and letters in a bearing number tell you about its dimensions and internal clearance. Correct installation procedures — heating methods, pressing methods, and the damage caused by incorrect installation. Bearing lubrication — grease versus oil lubrication, over-lubrication consequences, and lubrication intervals. Basic bearing failure modes — fatigue spalling, brinelling, fretting, and contamination — and what caused them." },
    { title: "Fasteners — Bolts, Nuts, and Torque", body: "Bolt grade identification — SAE grades (markings on bolt head) and metric property classes. Thread standards — UNC, UNF, and metric thread designation. Torque specifications — how they are determined, why they matter, and how to apply them correctly with a torque wrench. Bolt tightening patterns for flanges and multiple-bolt joints. Locking devices — lock washers, prevailing torque nuts, and thread locking compounds — when each is appropriate." },
    { title: "Seals and Gaskets", body: "Lip seals — installation direction, common installation damage, and replacement procedures. O-rings — material compatibility, correct sizing, and installation without damage. Mechanical seals — basic operating principle and the importance of correct installation and alignment. Gasket types — compressed fibre, spiral wound, ring joint — and the applications and torque requirements for each." },
    { title: "Basic Rigging", body: "Wire rope — construction designations (6×19, 6×37), inspection criteria for removal from service, and safe working load. Synthetic slings — types (web, round, chain), colour coding for capacity, and inspection requirements. Basic rigging configurations — straight, choker, and basket hitches and how each affects working load limit. Sling angle — how the angle between the sling leg and the load affects the tension in the sling and the effective capacity. D/d ratio for wire rope around hooks and pins." },
  ],
  catchOffGuardHeading: 'Where Year 1 Apprentices Lose Marks',
  catchOffGuard: [
    "Bearing knowledge is broad and detailed enough that surface familiarity is not enough. Apprentices who know bearing types in general but cannot identify failure modes from descriptions, or who cannot read a bearing designation, lose marks they should not. Study bearings thoroughly in Year 1 — it pays off in every subsequent year too.",
    "Rigging calculations with sling angles are mathematical and require practice. The relationship between sling angle and load on each leg is not intuitive and exam questions often test it numerically. Work through the calculations, not just the concept.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 1',
  howToUse: ["Study Mode is most valuable for Year 1 because the breadth of topics makes it easy to miss areas you did not know were tested. Going through every question with explanations ensures complete coverage. Use Quiz Mode to isolate your weakest topics — bearings, rigging math, and fastener specifications are the most commonly identified gaps. Full Exam Mode in your final week builds exam stamina and time awareness."],
});

// Millwright Year 2
add('millwright_2', {
  title: 'Millwright Year 2 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Study for your Year 2 millwright apprenticeship exam. Hydraulics, pneumatics, power transmission drives, and lubrication. Built on the curriculum.',
  h1: 'Millwright Industrial Mechanic — Year 2 Exam Prep',
  intro: "Year 2 of the millwright apprenticeship introduces fluid power systems and expands your power transmission knowledge. Hydraulics, pneumatics, belt and chain drives, couplings, pumps, and lubrication are the major topics. This is where the trade starts to feel most like industrial work — and the exam reflects that complexity. TradeBenchPrep gives you structured practice built on the  second period millwright curriculum.",
  needsToKnowHeading: 'What a Year 2 Millwright Apprentice Needs to Know',
  needsToKnow: [
    { title: "Hydraulics — Systems, Components, and Circuits", body: "Pascal's Law is the foundation: pressure applied to a confined fluid transmits equally in all directions. From there, know every major hydraulic system component — gear pumps, vane pumps, and piston pumps (fixed and variable displacement), directional control valves (2-way, 3-way, 4-way and their spool configurations), pressure control valves (relief, reducing, sequence, counterbalance), flow control valves, hydraulic cylinders (single and double acting), and hydraulic motors. Be able to read a hydraulic schematic using ISO symbols — identify each component from its symbol and trace circuit operation. Know how to calculate hydraulic force (F = P × A), flow rate, and cylinder speed. Hydraulic fluid properties — viscosity, cleanliness requirements, and the consequences of contaminated hydraulic fluid." },
    { title: "Pneumatics — Compressed Air Systems and Components", body: "Pneumatic systems use compressed air instead of hydraulic fluid. Know the components of a complete compressed air system — compressor, receiver tank, dryer, filter-regulator-lubricator (FRL) units, and distribution piping. Pneumatic directional control valves — 3-way and 5-way, spring return and detent, and how they control cylinder operation. Understand the differences in application between hydraulics and pneumatics — when each is appropriate and why. Air cylinder force calculations (F = P × A) and the effect of back pressure." },
    { title: "Lubrication — Oils, Greases, and Application", body: "Lubrication reduces friction and wear and is one of the most important maintenance responsibilities of a millwright. Know viscosity — what it means, how it is measured (ISO viscosity grade and SAE grade), and how to select the correct viscosity for an application based on operating speed and temperature. Grease — NLGI consistency grades, base oil viscosity in grease, and how to select the correct grease for bearings and other components. Lubrication methods — centralized lubrication systems, oil bath lubrication, splash lubrication, and the consequences of over-lubrication versus under-lubrication. Contamination — water, dirt, and incorrect lubricant mixing as primary causes of lubrication-related equipment failures." },
    { title: "Belt Drives — V-Belts and Synchronous Belts", body: "V-belt drive design — classical and narrow V-belt designations, sheave (pulley) design, and belt tensioning requirements. Speed ratio calculation (output RPM = input RPM × driver sheave diameter / driven sheave diameter). Belt tension — too little causes slippage and wear, too much causes bearing and shaft overload. Belt inspection — how to identify wear, glazing, cracking, and misalignment damage. Synchronous (timing) belt drives — how they differ from V-belts, their advantages (no slip, precise speed ratio), and installation requirements." },
    { title: "Chain Drives", body: "Roller chain — ANSI chain number designations, chain pitch, and how to select chain for a given application. Sprocket selection and speed ratio calculation. Chain tension and sag — correct sag measurement and adjustment. Chain lubrication — why it matters and correct lubrication methods for different operating environments. Chain wear measurement — how to measure chain elongation and when to replace a worn chain." },
    { title: "Couplings", body: "Rigid couplings — used only when shafts are in perfect alignment. Flexible couplings — jaw, gear, disc, and grid couplings — each has different misalignment tolerance and torsional stiffness characteristics. Know which type of coupling to select for a given application based on misalignment, torque, and speed. Coupling installation — shaft fit, keyway assembly, and why coupling alignment matters even for flexible types. Fluid couplings and torque converters — operating principles and applications in soft-start systems." },
    { title: "Centrifugal Pumps", body: "Know centrifugal pump construction — impeller, volute, wear rings, mechanical seal, and shaft. The pump curve — how head, flow, efficiency, and NPSH relate and how to find the operating point where the pump curve intersects the system curve. Cavitation — what causes it, what damage it causes, and how to prevent it. NPSH available versus NPSH required — the most important concept in pump installation. Pump priming — why centrifugal pumps must be primed and how to prime them correctly." },
  ],
  catchOffGuardHeading: 'What Year 2 Apprentices Find Most Challenging',
  catchOffGuard: [
    "Hydraulic schematic reading is the area where the gap between understanding and exam performance is largest. Many apprentices can describe what a hydraulic system does but struggle to read a schematic quickly enough to answer questions accurately under time pressure. Practice reading schematics actively — trace the circuit, identify every component, and describe what happens in each operating mode.",
    "Pump curves and NPSH concepts are theoretical but consistently tested. Understanding NPSH requires you to think about fluid pressure at the pump inlet in a way that is not always obvious from job experience alone. TradeBenchPrep's Study Mode explanations build this understanding step by step.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 2',
  howToUse: ["Hydraulic and pneumatic circuit questions reward repeated practice more than most other topics — use Quiz Mode specifically targeting fluid power until schematic reading feels fast and reliable. Drive calculation questions (speed ratios, belt tension, chain elongation) are mathematical and improve with repetition in Full Exam Mode under time pressure."],
});

// Millwright Year 3
add('millwright_3', {
  title: 'Millwright Year 3 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Prepare for your Year 3 millwright apprenticeship exam. Precision shaft alignment, vibration analysis, gearboxes, and compressors. curriculum aligned.',
  h1: 'Millwright Industrial Mechanic — Year 3 Exam Prep',
  intro: "Year 3 of the millwright apprenticeship is where precision maintenance becomes the focus. Shaft alignment, vibration analysis, advanced hydraulics, gearboxes, and compressors define the third period curriculum. These are the skills that distinguish a journeyman millwright from an apprentice, and the exam tests them in depth. TradeBenchPrep gives you practice built on the  Year 3 millwright curriculum.",
  needsToKnowHeading: 'What a Year 3 Millwright Apprentice Needs to Know',
  needsToKnow: [
    { title: "Precision Shaft Alignment", body: "Shaft misalignment is one of the leading causes of premature bearing and seal failure in rotating equipment. In Year 3 you need to know both concepts and mathematics of alignment. Understand the two types of misalignment — angular (shafts at an angle to each other) and parallel/offset (shaft centrelines parallel but not collinear). Dial indicator alignment — rim and face method and reverse dial indicator method: know how to set up the indicators, take readings at 12, 3, 6, and 9 o'clock positions, calculate misalignment from the readings, and determine the correct shim thickness and lateral movement required to correct both angular and offset misalignment simultaneously. Laser alignment systems — understand how they work and what they measure even if you are more familiar with dial indicators on the job. Soft foot — what it is, how to detect it (with a dial indicator), and why it must be corrected before performing precision alignment. Thermal growth — why machines that run hot need to be aligned cold with a calculated offset to be in alignment at operating temperature." },
    { title: "Vibration Analysis — Understanding What the Machine Is Telling You", body: "Vibration analysis is a predictive maintenance tool that lets a millwright diagnose problems in rotating equipment before failure occurs. You need to understand vibration frequency — measured in CPM (cycles per minute) or Hz — and how specific frequencies relate to specific fault types. Imbalance produces vibration at 1× running speed (1× RPM). Misalignment produces vibration at 1× and 2× running speed with a specific phase relationship. Mechanical looseness produces vibration at multiple harmonics (1×, 2×, 3×…). Rolling element bearing defects produce vibration at specific bearing defect frequencies (BPFO, BPFI, BSF, FTF) that are calculable from bearing geometry. Know what an overall vibration level tells you and what the spectrum (frequency breakdown) tells you that the overall number does not. Understand vibration severity criteria — what vibration levels are acceptable for different machine types and speeds." },
    { title: "Gearboxes and Speed Reducers", body: "Gear types used in industrial gearboxes — spur, helical, bevel, worm, and planetary gears — their load capacity characteristics, noise levels, and efficiency. Gearbox lubrication — oil level, viscosity selection, and change intervals. Gear backlash — what it is, why some is necessary, and what too much indicates. Gearbox inspection — what to look for when inspecting gear tooth wear, and how to identify pitting, spalling, and scuffing. Gearbox mounting — foot mounting, shaft mounting, and torque arm requirements for shaft-mounted reducers." },
    { title: "Compressors — Types and Maintenance", body: "Reciprocating compressors — piston and cylinder construction, valve operation, inter-cooling between stages, and common maintenance items (valve replacement, piston ring inspection). Rotary screw compressors — male and female rotor operation, oil injection and separation, and maintenance requirements. Centrifugal compressors — impeller operation, surge (what it is and why it is damaging), and stonewall. Know which compressor type is appropriate for different flow and pressure requirements and what the maintenance differences are." },
    { title: "Advanced Hydraulics — Proportional and Servo Systems", body: "Building on Year 2 hydraulic knowledge, Year 3 introduces proportional valves and servo valves that provide precise, variable control of flow and direction. Know how proportional valves differ from on/off directional valves — they can be positioned anywhere between fully open and fully closed providing proportional flow control. Servo valves provide even more precise control and are used in high-performance motion control applications. Hydraulic accumulators — bladder, diaphragm, and piston types — their function (energy storage, pulsation dampening, emergency power) and pre-charge pressure requirements." },
  ],
  catchOffGuardHeading: 'Where Year 3 Apprentices Should Focus Most',
  catchOffGuard: [
    "Shaft alignment mathematics is the most calculation-intensive topic in the millwright curriculum. The dial indicator method requires you to interpret readings, calculate misalignment values, and determine correction moves — all while accounting for indicator sag and the geometry of the machine being aligned. This is not a topic you can understand from reading alone. Work through alignment calculation problems repeatedly.",
    "Vibration frequency analysis — specifically matching fault frequencies to fault types — is tested with enough specificity that memorizing general concepts is insufficient. Know the frequency signature of each fault type and be able to apply it to a given running speed.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 3',
  howToUse: ["Quiz Mode targeting alignment and vibration topics is the most efficient preparation for the highest-value Year 3 content. Full Exam Mode in your final preparation weeks is essential — Year 3 is the most demanding exam to this point in the apprenticeship and stamina matters."],
});

// Millwright Year 4
add('millwright_4', {
  title: 'Millwright Year 4 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Study for your Year 4 millwright apprenticeship exam. Predictive maintenance, advanced troubleshooting, and full curriculum coverage. Journeyman prep.',
  h1: 'Millwright Industrial Mechanic — Year 4 Exam Prep',
  intro: "Year 4 is the final period of the millwright apprenticeship. Predictive maintenance technologies, advanced troubleshooting, field balancing, and the integration of everything from the previous three years define the fourth period. Completing Year 4 qualifies you to challenge the Interprovincial exam for your journeyman industrial mechanic certificate. TradeBenchPrep gives you the comprehensive, curriculum-aligned practice you need to finish your apprenticeship at the highest level.",
  needsToKnowHeading: 'What a Year 4 Millwright Apprentice Needs to Know',
  needsToKnow: [
    { title: "Predictive Maintenance Technologies", body: "Condition monitoring is the systematic collection of machine data to detect developing faults before they cause failure. Know the four primary predictive maintenance technologies: Vibration analysis — already introduced in Year 3, Year 4 deepens this knowledge into trend analysis and alarm level setting. Thermography (infrared) — how thermal cameras detect hot spots from electrical faults, bearing failures, refractory degradation, and steam trap failures. Know what a thermal image tells you and its limitations. Ultrasonic testing — how ultrasound detects air and gas leaks, steam trap condition, bearing early-stage defects (before they appear in vibration), and electrical discharge (arcing, tracking, corona). Oil analysis — what a complete oil analysis report includes (viscosity, contamination particle count, water content, wear metals, and additive depletion), what each parameter indicates about machine condition, and when to act on results. Understand how to build a complete predictive maintenance program using these technologies together rather than in isolation." },
    { title: "Field Balancing of Rotating Equipment", body: "Static versus dynamic imbalance — understand the difference and what each produces in terms of vibration signature. Single-plane balancing — the influence coefficient method using a vibration analyzer: how to take reference readings, add a trial weight, calculate the correction weight mass and location from the vector change, and verify the correction. Two-plane balancing — the additional complexity of coupled planes and how correction in one plane affects the other. Know when single-plane balancing is sufficient and when two-plane balancing is required." },
    { title: "Advanced Troubleshooting — Systematic Methodology", body: "Year 4 troubleshooting goes beyond identifying single-component failures to diagnosing problems in complex integrated systems. Know and apply a systematic troubleshooting process: define the problem precisely, collect operating data, identify possible causes, test hypotheses starting with the most likely and least invasive, implement the correction, and verify the result. Multi-system troubleshooting — when a symptom could have hydraulic, mechanical, or control system causes, know how to isolate each system systematically. Root cause analysis — distinguishing between the failure mode (what failed), the mechanism (how it failed), and the root cause (why it failed) to prevent recurrence." },
    { title: "Condition Monitoring Program Design", body: "Understanding not just how to use predictive maintenance tools but how to design and implement a program. Route-based versus online monitoring — when each approach is appropriate. Setting alarm levels — the difference between absolute alarms based on published standards and relative alarms based on trend change from baseline. Equipment criticality ranking — how to prioritize monitoring resources based on the consequence of failure and the replaceability of equipment." },
    { title: "Review and Integration — The Full Four Years", body: "The Year 4 exam draws from the complete millwright curriculum. Bearing knowledge from Year 1, hydraulic systems from Year 2, alignment from Year 3, and predictive maintenance from Year 4 all appear. No previous year's content should be considered out of scope for the Year 4 exam. The most effective preparation covers all four years with emphasis on Year 3 and Year 4 content." },
  ],
  catchOffGuardHeading: null,
  catchOffGuard: [],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 4',
  howToUse: ["Full Exam Mode is your primary preparation tool in Year 4. Run complete timed exams repeatedly and use your dashboard analytics to identify which topic areas are dragging your score. Predictive maintenance technology questions — thermography, ultrasonic, and oil analysis — are Year 4-specific and may not be reinforced by your job experience. Study Mode for these topics ensures you have the complete knowledge the exam requires regardless of your site exposure."],
});

// --- Steamfitter / Pipefitter Year 1 ---
add('steamfitter-pipefitter_1', {
  title: 'Steamfitter Pipefitter Year 1 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: "Preparing for your Year 1 steamfitter/pipefitter apprenticeship exam? Learn what the period exam covers — pipe materials, joining methods, blueprints, and safety.",
  h1: 'Steamfitter / Pipefitter — Year 1 Exam Prep',
  intro: "Year 1 of the steamfitter/pipefitter apprenticeship builds the foundation — pipe materials, joining methods, tools, safety, and basic blueprint reading. The first period exam is broad, covering a lot of introductory content, and the apprentices who do best are those who study systematically rather than assuming job experience covers the gaps. TradeBenchPrep is built on the  first period curriculum to give you exactly that preparation.",
  needsToKnowHeading: 'What a Year 1 Steamfitter/Pipefitter Apprentice Needs to Know',
  needsToKnow: [
    { title: "Workplace Safety — Critical in Every Period", body: "WHMIS 2015, PPE selection for piping environments (face shields for chemical exposure, respiratory protection for soldering and brazing fumes, fall protection for elevated work), and lockout/tagout procedures step by step. Confined space awareness — the definition of a confined space, permit-required confined spaces, and the roles of entrants, attendants, and supervisors. Hot work safety — fire watch requirements, fire extinguisher placement, and safe work permits. Safety knowledge is heavily weighted in Year 1 and present in every subsequent exam." },
    { title: "Pipe Materials — Properties and Applications", body: "Carbon steel pipe — schedule designation (Schedule 40, 80, 160 and XXH), outside diameter standardization, and applications in steam, water, and gas systems. Stainless steel — austenitic grades (304, 316) and their applications where corrosion resistance is required. Copper — types (K, L, M and DWV) and their wall thickness and pressure rating differences. CPVC and PVC plastic pipe — pressure ratings, temperature limitations, and the critical importance of correct solvent cement selection and application. Knowing which material is correct for a given service (temperature, pressure, fluid) is foundational pipefitter knowledge that appears throughout all four years." },
    { title: "Pipe Joining Methods", body: "Threaded joints — NPT (National Pipe Taper) thread standard, how to cut threads correctly, thread engagement length, and pipe thread sealant selection (Teflon tape versus pipe dope and when each is appropriate). Flanged joints — flange types (weld neck, slip-on, threaded, blind), gasket selection, bolt patterns, and correct torquing sequence for leak-free joints. Soldering and brazing — the difference between soldering (below 450°C) and brazing (above 450°C), correct flux selection, and heat application technique. Socket weld and butt weld joints — how they differ and when each is used. Mechanical couplings — Victaulic and similar groove-and-coupling systems." },
    { title: "Hand Tools and Pipe-Specific Tools", body: "Pipe cutters, pipe reamers, threading machines, and pipe vises — know the correct use and maintenance of each. Tube cutters for copper. Pipe wrenches — correct sizing for the pipe being worked on and the damage caused by using an oversized wrench. Measuring and layout — tape measure, level, plumb bob, and laser level use in piping installation." },
    { title: "Blueprint Reading — Introduction to Piping Drawings", body: "Orthographic projection — how plan (top view), elevation (side view), and section views relate to each other. Isometric piping drawings — how to read a piping isometric, identify pipe size and material, locate fittings, and extract dimensions. P&ID symbols — know the standard symbols for pipe, valves (gate, globe, ball, butterfly, check), instruments (pressure gauge, temperature gauge, flow meter), and equipment. Ability to read blueprints is tested at every level of the apprenticeship — start building this skill in Year 1." },
    { title: "Fittings and Their Applications", body: "Elbows (45° and 90°, long radius and short radius), tees, reducers, unions, couplings, caps, and plugs — know the purpose of each and when each is used. The difference between a concentric and eccentric reducer and why it matters (eccentric reducers maintain bottom-of-pipe or top-of-pipe alignment, important for drainage and gas systems). Fitting allowances — how to calculate the cut length of pipe when accounting for fitting takeout and thread engagement." },
    { title: "Pipe Supports and Hangers", body: "Pipe support types — clevis hangers, riser clamps, pipe shoes, and spring hangers. Support spacing requirements based on pipe size and material. The importance of pipe support in preventing sag (which causes drainage problems and stress concentrations) and controlling thermal expansion movement." },
  ],
  catchOffGuardHeading: 'Where Year 1 Apprentices Lose Marks',
  catchOffGuard: [
    "Blueprint reading is consistently the area where apprentices with strong practical skills underperform on the exam. Being able to read an isometric drawing and a P&ID requires specific knowledge of symbols and conventions that are not always learned on the job. Study blueprint reading actively — practice identifying symbols and extracting information from sample drawings.",
    "Fitting allowances and cut length calculations require accurate arithmetic and knowledge of specific fitting dimensions. Work through multiple practice calculations before your exam.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 1',
  howToUse: ["Study Mode is particularly valuable in Year 1 for ensuring you have not missed any topic areas. The breadth of first period content makes it easy to overlook something. Quiz Mode lets you test yourself on the areas you feel least confident about. Full Exam Mode builds exam stamina before your actual exam date."],
});

// Steamfitter Year 2
add('steamfitter-pipefitter_2', {
  title: 'Steamfitter Pipefitter Year 2 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Study for your Year 2 steamfitter/pipefitter apprenticeship exam. Steam systems, hydronic heating, valves, and piping codes. Built on the curriculum.',
  h1: 'Steamfitter / Pipefitter — Year 2 Exam Prep',
  intro: "Year 2 of the steamfitter/pipefitter apprenticeship moves from foundational skills to applied system knowledge. Steam systems, hydronic heating, valves, and intermediate piping code application are the core of second period content. This is where the steamfitter designation becomes most apparent — steam systems are central to the Year 2 curriculum and the exam reflects that depth. TradeBenchPrep gives you targeted practice built on the  Year 2 curriculum.",
  needsToKnowHeading: 'What a Year 2 Steamfitter/Pipefitter Apprentice Needs to Know',
  needsToKnow: [
    { title: "Steam Systems — The Heart of the Steamfitter Trade", body: "Steam generation — know how a boiler generates steam, the difference between fire-tube and water-tube boilers, and the controls and safety devices that protect a boiler (pressure relief valve, low water cutoff, high limit controls). Steam properties — saturated steam versus superheated steam, steam tables and how to use them to find temperature, pressure, enthalpy, and specific volume. Steam distribution — steam mains, drip legs, and the importance of proper steam pipe pitch for condensate drainage. Steam traps — the most important single component in a steam distribution system. Know the three types: mechanical (float and thermostatic), thermodynamic (disc), and thermostatic (bimetallic). Know how each works, its advantages and disadvantages, and how to test whether a trap is working, failed open, or failed closed. Condensate return systems — why returning condensate is important (energy efficiency, water treatment costs), flash steam, and condensate pump and receiver systems." },
    { title: "Hydronic Heating Systems", body: "Hot water heating — how a hydronic heating system circulates hot water from a boiler through terminal units (radiators, fan coil units, radiant floor panels) and back. System components — circulating pumps, expansion tanks (open, closed, and bladder types), air separators, pressure relief valves, and fill valves. Balancing — why a hydronic system must be balanced and how balancing valves are used to ensure correct flow to each terminal unit. Two-pipe versus one-pipe systems — how each is piped and the advantages of the two-pipe system for temperature control. Radiant floor heating — how it works and what makes it different from other hydronic terminal units." },
    { title: "Valves — Types, Selection, and Application", body: "Gate valves — full-bore, bi-directional flow, not for throttling. Globe valves — for throttling service, pressure drop through the valve. Ball valves — quarter-turn operation, full bore or reduced bore, excellent shut-off. Butterfly valves — compact and lightweight, used for larger pipe sizes. Check valves — swing check, lift check, and wafer check — prevent reverse flow. Pressure reducing valves — how they maintain downstream pressure independent of upstream pressure variations. Safety relief valves — how they are sized and tested. Knowing which valve type to select for a given application — and why a gate valve must never be used for throttling — is tested in every period of the apprenticeship." },
    { title: "Intermediate Piping Code — B31.1 and B31.3", body: "B31.1 covers power piping (steam, condensate, and feedwater piping in power plants). B31.3 covers process piping (industrial process plant piping). Know what each code governs, its general organization, and the key requirements for pipe material, pressure ratings, joining methods, testing, and documentation. Be able to navigate each code to find specific requirements — code navigation speed matters under exam conditions." },
    { title: "Insulation and Heat Tracing", body: "Insulation types — fiberglass, mineral wool, calcium silicate (for high temperature), and cellular glass (for cold service). Insulation thickness selection based on pipe temperature, ambient temperature, and energy loss requirements. Electric heat tracing — how self-regulating heat trace cable works and its applications in freeze protection. Steam heat tracing — traced lines, tracing tubing sizing, and the steam trap at the tracing outlet." },
  ],
  catchOffGuardHeading: 'What Year 2 Apprentices Must Know Cold',
  catchOffGuard: [
    "Steam trap operation is one of the most important and most tested topics in the steamfitter trade. Know all three trap types — mechanical, thermodynamic, and thermostatic — their operation, their failure modes, and how to test them. You cannot know steam traps too well.",
    "Valve selection — knowing not just the names of valve types but specifically when each is and is not appropriate — is a Year 2 topic that carries through to every subsequent year. Study it thoroughly.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 2',
  howToUse: ["Steam system questions in Study Mode are essential preparation — the depth of steam content in Year 2 rewards methodical study over quick review. For valve and code application questions, Quiz Mode targeting those specific areas is most efficient. Full Exam Mode in your final preparation weeks ensures you are ready for the full breadth of Year 2 content."],
});

// Steamfitter Year 3
add('steamfitter-pipefitter_3', {
  title: 'Steamfitter Pipefitter Year 3 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Prepare for your Year 3 steamfitter/pipefitter apprenticeship exam. Process piping, refrigeration systems, pressure testing, and advanced codes. curriculum aligned.',
  h1: 'Steamfitter / Pipefitter — Year 3 Exam Prep',
  intro: "Year 3 of the steamfitter/pipefitter apprenticeship advances into industrial process piping and refrigeration systems. The technical depth increases significantly and the piping codes become more complex. This is where the industrial character of the pipefitter trade becomes most apparent. TradeBenchPrep provides practice built on the  Year 3 curriculum to prepare you for the most demanding exam in the program to this point.",
  needsToKnowHeading: 'What a Year 3 Steamfitter/Pipefitter Apprentice Needs to Know',
  needsToKnow: [
    { title: "Refrigeration Systems — Cycle, Components, and Application", body: "The vapour compression refrigeration cycle is the foundation of all mechanical refrigeration. Know the four components and what happens to the refrigerant at each: compressor (low-pressure vapour → high-pressure vapour), condenser (high-pressure vapour → high-pressure liquid, heat rejected), expansion device (high-pressure liquid → low-pressure liquid/vapour mixture), evaporator (low-pressure mixture → low-pressure vapour, heat absorbed). Refrigerants — HFCs (R-134a, R-410A), HFOs, and the phase-out of HCFCs. Know why refrigerant choice matters (environmental impact, operating pressure, toxicity) and the regulatory requirements around refrigerant handling in Canada. Compressor types in refrigeration — reciprocating, rotary, scroll, and screw compressors — their operating principles and typical applications. Expansion devices — thermostatic expansion valve (TXV) and electronic expansion valve (EEV) — how each regulates refrigerant flow based on superheat. Superheat and subcooling — what they are, how to measure them, and what abnormal readings indicate about system performance." },
    { title: "Process Piping — Industrial Systems", body: "Process piping in oil and gas, petrochemical, and industrial plant environments. Alloy piping materials — chrome-moly (P91, P22), duplex stainless, and Hastelloy — and why they are specified for high-temperature, high-pressure, or corrosive service. Piping stress and flexibility — why piping systems need to be designed with loops and offsets to absorb thermal expansion without overstressing equipment connections and supports. Pipe stress software is used for design but understanding the concepts is required for the exam. Specialty fittings — weld-o-lets, thread-o-lets, and sock-o-lets as branch connections without tees." },
    { title: "Advanced Piping Codes", body: "Deeper application of B31.3 including material specifications (P-numbers and their significance), examination categories (normal, Category D, and Category M fluid service), required NDE for different examination categories, and pressure test requirements. Understand the difference between a hydrostatic test and a pneumatic test — when each is used, the safety concerns with each, and the specific requirements (test pressure, hold time, and what constitutes a successful test). Welding procedure specifications and their application under B31.3 — know what an WPS contains and what essential variables require re-qualification." },
    { title: "Pressure Testing — Procedures and Safety", body: "Hydrostatic testing — fill the system with water, pressurize to 1.5× the design pressure, and hold for a specified time while inspecting for leaks. Why water is preferred (incompressible — a failure releases the pressure without explosive energy release). Pneumatic testing — used when hydrostatic testing is not practical (weight of water would overstress the structure, or the system cannot tolerate moisture). Pressurize with air or nitrogen to 1.1× the design pressure. Higher risk than hydrostatic — compressed gas stores significant energy. Know the safety precautions — blast shields, evacuation zones, and leak detection with soap solution. Test documentation — pressure test records, including test medium, test pressure, gauge calibration records, and witness signatures." },
    { title: "Instrumentation for Pipefitters", body: "P&ID instrumentation symbols at an advanced level — tag numbering systems, instrument function letters, and how to read a complete P&ID to understand what each instrument measures and controls. Pressure gauges — Bourdon tube operating principle, gauge selection, pulsation dampeners, and root valve requirements. Temperature measurement — thermocouples and RTDs, thermowell installation, and immersion length. Flow measurement — orifice plates, magnetic flowmeters, and vortex meters — operating principles and installation requirements (upstream and downstream straight pipe requirements)." },
  ],
  catchOffGuardHeading: 'Year 3 Topics That Reward the Most Study Time',
  catchOffGuard: [
    "Refrigeration cycle knowledge is Year 3-specific and may not be reinforced by your job experience if you work primarily in steam or process environments. The exam expects complete knowledge of the refrigeration cycle, refrigerant properties, expansion valve operation, and superheat/subcooling measurement. Study this systematically.",
    "Pressure testing procedures — specifically the distinction between hydrostatic and pneumatic testing, the safety requirements for each, and the documentation requirements — is consistently tested and rewards thorough preparation.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 3',
  howToUse: ["Refrigeration and process piping questions in Study Mode ensure complete coverage of topics that may not be reinforced by your specific job experience. Quiz Mode for code application questions — particularly B31.3 examination categories and test requirements — is the most efficient targeted preparation. Full Exam Mode is essential to build stamina for the most comprehensive exam to this point in the apprenticeship."],
});

// Steamfitter Year 4
add('steamfitter-pipefitter_4', {
  title: 'Steamfitter Pipefitter Year 4 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Study for your Year 4 steamfitter/pipefitter apprenticeship exam. Advanced industrial systems, commissioning, and comprehensive code mastery. Journeyman prep.',
  h1: 'Steamfitter / Pipefitter — Year 4 Exam Prep',
  intro: "Year 4 is the final period of the steamfitter/pipefitter apprenticeship. Advanced industrial piping systems, system commissioning, project coordination, and comprehensive mastery of applicable codes define the fourth period curriculum. Completing Year 4 qualifies you to challenge the Interprovincial exam for your journeyman steamfitter/pipefitter certificate. TradeBenchPrep gives you the curriculum-aligned practice to finish at your best.",
  needsToKnowHeading: 'What a Year 4 Steamfitter/Pipefitter Apprentice Needs to Know',
  needsToKnow: [
    { title: "Advanced Industrial Piping Systems", body: "High-pressure steam systems — supercritical steam, alloy piping, and the additional code requirements that apply at elevated pressures and temperatures. Cryogenic piping — materials that remain ductile at very low temperatures (stainless steel, aluminum, copper), insulation systems, and the design considerations unique to cryogenic service. Specialty system piping — oxygen service (cleanliness requirements and the hazard of oil contamination in oxygen piping), chlorine service, and other specialty fluid services with specific material and installation requirements." },
    { title: "System Commissioning", body: "Pre-commissioning activities — system walk-down and punch list completion, flushing and cleaning procedures (water flushing, chemical cleaning, steam blowing), hydrostatic testing completion and documentation, and insulation completion verification. Commissioning startup sequences — valve alignment, vent and drain procedures, gradual pressurization and temperature ramp-up, and initial performance checks. Commissioning documentation — system turnover packages, test records, and as-built drawing updates. Understanding the complete commissioning process from construction completion to handover to operations is important Year 4 knowledge." },
    { title: "Project Coordination for Pipefitters", body: "Shutdown planning — how major equipment tie-ins and system modifications are planned to minimize production impact. Isolation planning — developing isolation lists, blind lists, and lockout/tagout packages for complex systems. Work package preparation — how to organize the work sequence, material requirements, and resource needs for a piping installation or maintenance scope." },
    { title: "Comprehensive Code Mastery", body: "The Year 4 exam expects you to apply piping codes to the full range of scenarios encountered in industrial work. B31.1 and B31.3 in depth — know the structure of each code well enough to navigate to any requirement quickly. ASME Boiler and Pressure Vessel Code (BPVC) Section I for power boilers and Section VIII for pressure vessels — understand what each governs and how they interface with B31.1 piping. CSA B149 gas codes — requirements for natural gas and propane piping in industrial facilities." },
    { title: "Review and Integration", body: "The Year 4 exam draws from the complete four-year curriculum. Steam system knowledge from Year 2, refrigeration from Year 3, and advanced industrial systems from Year 4 are all in scope. Comprehensive preparation across all years is necessary, with the heaviest emphasis on Years 3 and 4 content." },
  ],
  catchOffGuardHeading: null,
  catchOffGuard: [],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 4',
  howToUse: ["Full Exam Mode is the most important preparation tool at Year 4. The final period exam is the most comprehensive of the apprenticeship and sustained performance across a long exam requires practice. Use your dashboard results to identify and address weak areas in your final weeks of preparation. Study Mode for commissioning and advanced system content ensures you are not caught off guard by Year 4-specific topics that may be outside your direct job experience."],
});

// --- Welder Year 1 ---
add('welder_1', {
  title: 'Welder Year 1 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: "Preparing for your Year 1 welder apprenticeship exam? Learn what the period exam covers — SMAW, electrode classification, joint design, weld symbols, and safety.",
  h1: 'Welder — Year 1 Exam Prep',
  intro: "Year 1 of the welder apprenticeship establishes the foundational knowledge that every subsequent year builds on. SMAW process theory, electrode classification, joint design, weld symbols, basic metallurgy, and workplace safety form the core of first period content. The Year 1 exam is broad and rewards apprentices who have studied systematically. TradeBenchPrep is built on the  welding curriculum to give you the structured practice you need.",
  needsToKnowHeading: 'What a Year 1 Welder Apprentice Needs to Know',
  needsToKnow: [
    { title: "Workplace Safety — Welding-Specific Hazards", body: "Welding safety goes beyond general workplace safety. Fume and gas hazards — welding fumes are a complex mixture of metallic oxides and gases (ozone, nitrogen oxides, carbon monoxide) that require engineering controls (local exhaust ventilation) and respiratory protection when ventilation is insufficient. Know the specific hazards of welding on coated materials — galvanizing (zinc fumes causing metal fume fever), lead paint, and cadmium-plated materials. Arc flash and UV radiation — know the correct lens shade for different welding processes and currents. Electrical safety in welding — proper grounding, cable condition inspection, and working in wet environments. Fire prevention — hot work permits, fire watch requirements, and the minimum distances for combustibles. Confined space welding — additional ventilation and monitoring requirements." },
    { title: "Basic Metallurgy — Know What You Are Welding", body: "Ferrous metals — carbon steel classifications (low, medium, and high carbon steel) and how carbon content affects weldability. The higher the carbon content, the more difficult the steel is to weld without cracking. Non-ferrous metals introduced in Year 1 — aluminum, copper, and their basic welding characteristics. Metal identification methods — spark test, magnet test, and chemical tests for field identification of unknown metals. Crystal structure basics — how metals solidify from liquid, grain structure, and how grain size affects mechanical properties." },
    { title: "SMAW — Shielded Metal Arc Welding Theory", body: "SMAW is the process covered in depth in Year 1. Know the complete SMAW process: DC versus AC power sources — the difference between DCEP (electrode positive, deeper penetration), DCEN (electrode negative, less penetration and heat input), and AC (used with certain electrodes). Arc length — too long causes porosity, voltage fluctuation, and spatter; too short causes stubbing and electrode sticking. Travel speed — too fast causes a narrow, convex bead; too slow causes excessive buildup, undercut, and burn-through. Electrode angle — work angle (90° to the joint) and travel angle (5–15° drag angle for most applications)." },
    { title: "Electrode Classification — The AWS System", body: "The AWS electrode classification system is one of the most testable topics in Year 1 and you must know it completely. For SMAW electrodes (E XXXX format): E = electrode, first two or three digits = minimum tensile strength in ksi (E7018 = 70,000 psi tensile strength), second-to-last digit = welding positions (1 = all positions, 2 = flat and horizontal only), last digit = coating type and current type (8 = low hydrogen, DCEP or AC). Know the most common electrodes: E6010 (deep penetrating, DCEP, all positions, used for root passes in pipeline and structural work), E6011 (similar to E6010 but AC capable), E6013 (easy to use, AC or DC, for general purpose), E7018 (low hydrogen, DCEP or AC, for structural work requiring good impact properties). Low hydrogen electrodes — why they require storage in a heated oven and reconditioning of exposed electrodes." },
    { title: "Joint Design and Weld Types", body: "Joint types — butt joint, T-joint, corner joint, lap joint, and edge joint. Weld types — groove weld, fillet weld, plug weld, and slot weld. Groove weld preparations — square groove, V-groove, bevel groove, J-groove, and U-groove — and when each is used based on material thickness and access. Root opening, root face, and groove angle — what each term means and how they affect the weld. Fillet weld geometry — leg size, throat size, and the difference between theoretical throat and effective throat." },
    { title: "Weld Symbols — The AWS System", body: "The AWS welding symbol is the universal language of fabrication and structural welding. Know every element of the complete welding symbol: reference line, arrow, weld symbol (placed below the reference line for arrow side, above for other side), dimensions (size, length, pitch for intermittent welds), finish symbol, contour symbol, field weld flag, and all-around symbol. Be able to read a weld symbol from a drawing and know exactly what weld to make — size, type, location, contour, and finish required." },
    { title: "Blueprint Reading for Welding", body: "Welding drawings — how to read an engineering drawing for a weldment, including detail views, section views, and welding symbol placement. Bill of materials — how to read a parts list and understand material specifications including material grade designations. Basic fabrication sequences — understanding how a weldment is assembled and in what order welds are made to control distortion." },
  ],
  catchOffGuardHeading: 'What Year 1 Welders Must Know Without Hesitation',
  catchOffGuard: [
    "Electrode classification — you must be able to decode any AWS SMAW electrode designation immediately. This is tested directly and also embedded in scenario questions throughout the exam. Do not leave this to memory — understand the system so you can decode any electrode you see.",
    "Weld symbols — the exam assumes you can read a complete welding symbol accurately. Errors in symbol interpretation lead to wrong welds, which is a safety issue in structural and pressure applications. Study the complete symbol system until it is automatic.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 1',
  howToUse: ["Study Mode for electrode classification and weld symbol questions gives you the explanations needed to understand the system rather than just memorize examples. Quiz Mode on these specific topics is the most efficient way to build speed and confidence. Full Exam Mode in the week before your exam ensures you are comfortable with the breadth of Year 1 content under time pressure."],
});

// Welder Year 2
add('welder_2', {
  title: 'Welder Year 2 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Study for your Year 2 welder apprenticeship exam. GMAW, FCAW, GTAW, intermediate metallurgy, distortion control, and weld defects. curriculum aligned.',
  h1: 'Welder — Year 2 Exam Prep',
  intro: "Year 2 of the welder apprenticeship significantly expands your process knowledge. GMAW (MIG), FCAW, and GTAW (TIG) join SMAW as processes you must understand in depth. Intermediate metallurgy, weld distortion, weld defects, and more detailed code awareness define the second period curriculum. TradeBenchPrep gives you practice built on the  Year 2 welding curriculum.",
  needsToKnowHeading: 'What a Year 2 Welder Apprentice Needs to Know',
  needsToKnow: [
    { title: "GMAW — Gas Metal Arc Welding (MIG)", body: "GMAW process fundamentals — the wire electrode is fed continuously through the welding gun and the arc is shielded by externally supplied shielding gas. Know the four metal transfer modes: Short circuit transfer — low voltage and wire feed speed, wire touches the puddle and shorts, creating a small weld with low heat input. Used for thin materials and out-of-position welding. Globular transfer — higher voltage, molten drops larger than the wire diameter fall into the puddle irregularly, high spatter. Spray transfer — high voltage and wire feed speed, very fine droplets transfer axially across the arc in a continuous stream, very smooth bead, high deposition rate, flat and horizontal only. Pulse transfer — rapidly alternates between high and low current, achieves spray-like droplet transfer at lower average heat input, all-position capable. Shielding gas selection — 100% CO₂ (deep penetration, high spatter), 75%Ar/25%CO₂ (C25, the most common all-purpose mix for carbon steel), and argon-rich mixes for stainless and aluminum. Wire classification — AWS ER70S-6 is the most common carbon steel GMAW wire — know what each designation element means." },
    { title: "FCAW — Flux Cored Arc Welding", body: "Two types of FCAW: Gas-shielded FCAW (FCAW-G) — requires external shielding gas similar to GMAW, produces high quality welds, used in fabrication shops. Self-shielded FCAW (FCAW-S) — no external gas required, the flux core generates its own shielding, more portable for field work, more sensitive to technique. Wire classification — E71T-1 (gas-shielded, all-position, excellent for structural) and E71T-11 (self-shielded, all-position) are the most common. Know when FCAW is preferred over SMAW or GMAW — high deposition rate for production welding on heavier sections, field work capability with self-shielded wire." },
    { title: "GTAW — Gas Tungsten Arc Welding (TIG)", body: "GTAW uses a non-consumable tungsten electrode to create the arc and filler metal is added separately by hand. This produces the highest quality, most controlled weld of any arc welding process. Tungsten electrode types — pure tungsten (green, for AC aluminum welding), 2% thoriated (red, DCEN for steel and stainless — being phased out for radioactivity concerns), 2% ceriated (grey, DCEN for steel, stainless, and some aluminum applications, now the preferred alternative to thoriated). Tungsten preparation — for DCEN, grind the tungsten to a point with the grind marks running lengthwise. For AC, allow the tungsten to form a hemispherical ball. Shielding gas — argon for most GTAW applications, helium for higher heat input requirements, argon/helium mixtures. Back purging — why the back side of a stainless or titanium root pass must be shielded with argon to prevent oxidation. Current selection — DCEN for steel, stainless, copper. AC for aluminum (the positive half-cycle removes the oxide layer)." },
    { title: "Intermediate Metallurgy — Heat Effects on Metal", body: "The iron-carbon phase diagram — the basis for understanding how steel transforms through heating and cooling. Know the critical temperature (approximately 723°C for eutectoid transformation) and how it relates to heat treatment and preheat requirements. Heat affected zone (HAZ) — the region adjacent to the weld that has been heated above the critical temperature but not melted. The HAZ experiences metallurgical changes including grain growth, hard martensite formation in higher-carbon steels, and sensitization in austenitic stainless steels. Carbon equivalent (CE) — the formula that combines carbon content and alloying elements to predict weldability and preheat requirements. Higher CE = higher preheat required to prevent hydrogen-assisted cracking. Preheat — heating the base metal before welding to slow the cooling rate, reduce hard martensite formation, and allow hydrogen to diffuse out. Post-weld heat treatment (PWHT) — stress relief annealing to reduce residual stresses in thick sections and certain alloy steels." },
    { title: "Weld Distortion — Causes and Control", body: "Distortion is caused by differential thermal expansion and contraction during welding — the weld metal and HAZ contract on cooling and pull the surrounding base metal with them. Types of distortion — angular distortion (the plate bends away from the weld), longitudinal shrinkage (the weld gets shorter as it cools), and transverse shrinkage (the joint closes up). Distortion control methods — pre-setting (welding the joint at an angle opposite to the expected distortion so it comes out straight when distortion occurs), back-step welding (welding short segments in the direction opposite to the overall progression to distribute heat more evenly), balanced welding (alternating welds on both sides of a neutral axis), and fixturing (clamping or tacking the assembly to resist movement). Residual stress — internal stresses that remain in the weldment after it has cooled. High residual stresses increase the susceptibility to fatigue cracking and stress corrosion." },
    { title: "Weld Defects — Types, Causes, and Prevention", body: "Know every major weld defect — what it looks like, what causes it, and how to prevent it: Porosity (gas pockets in the weld) — caused by contamination (moisture, oil, rust, mill scale), insufficient shielding gas coverage, or too long an arc. Undercut (groove at the weld toe that reduces the base metal cross-section) — caused by too high a current, too fast a travel speed, or incorrect electrode angle. Incomplete fusion — caused by too low a heat input, incorrect technique, or a contaminated joint surface. Incomplete penetration (in groove welds) — caused by too small a root opening, too large a root face, or insufficient current. Overlap (weld metal rolls over the base metal surface without fusing to it) — caused by too low a current or too slow a travel speed. Cracks — hot cracks (solidification cracks that form in the weld metal while it is still hot) caused by high sulfur or phosphorus content or highly restrained joints. Cold cracks (hydrogen-assisted cracks) — form after cooling, caused by hydrogen in the weld, a susceptible microstructure (martensite), and residual tensile stress. Prevented by low-hydrogen electrodes, preheat, and proper PWHT." },
  ],
  catchOffGuardHeading: 'What Year 2 Welders Must Understand Deeply',
  catchOffGuard: [
    "GMAW transfer modes are the most commonly tested Year 2 topic and require understanding beyond just naming the modes. Know what parameters produce each mode, what the weld bead looks like, what the spatter level is, and what applications each mode is suited for.",
    "Cold cracking (hydrogen-assisted cracking) — understanding why it occurs (hydrogen + martensite + tensile stress) is more important than memorizing the name. This understanding lets you answer questions about prevention (low hydrogen consumables, preheat, PWHT) correctly even if they are phrased in unfamiliar ways.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 2',
  howToUse: ["Study Mode for GMAW transfer modes and weld defect questions gives you the detailed explanations that build the understanding needed for both Year 2 and Year 3 exams. Quiz Mode for GTAW electrode and current selection questions is most efficient for that specific topic. Full Exam Mode with timed conditions is essential in your final week of preparation."],
});

// Welder Year 3
add('welder_3', {
  title: 'Welder Year 3 Exam Prep | Apprenticeship | TradeBenchPrep',
  metaDescription: 'Prepare for your Year 3 welder apprenticeship exam. Advanced metallurgy, pressure codes, SAW, NDE, and welding procedure specifications. curriculum aligned.',
  h1: 'Welder — Year 3 Exam Prep',
  intro: "Year 3 is the final period of the welder apprenticeship and the most technically advanced. Advanced metallurgy including stainless steel and aluminum, submerged arc welding, pressure vessel and pressure piping codes, non-destructive examination, and welding procedure specifications define the third period curriculum. Completing Year 3 qualifies you to challenge the Interprovincial exam for your journeyman welder certificate. TradeBenchPrep gives you the comprehensive, curriculum-aligned practice to finish your apprenticeship at the highest level.",
  needsToKnowHeading: 'What a Year 3 Welder Apprentice Needs to Know',
  needsToKnow: [
    { title: "Advanced Metallurgy — Stainless Steel", body: "Austenitic stainless steels (300 series — 304, 316, 321, 347) — austenitic structure gives them excellent corrosion resistance, good toughness, and non-magnetic properties. The key welding challenge is sensitization — when austenitic stainless is heated in the range of 425–870°C (the sensitization range), chromium carbides precipitate at grain boundaries, depleting chromium from the surrounding metal and creating zones that are susceptible to intergranular corrosion. Prevention methods: use low carbon grades (304L, 316L), use stabilized grades that contain titanium or niobium to preferentially combine with carbon (321, 347), use solution annealing after welding if possible, or minimize time in the sensitization range by limiting heat input and interpass temperature. Ferritic stainless steels (400 series — 430) — magnetic, less corrosion resistant than austenitic, susceptible to grain growth in the HAZ and sensitization. Duplex stainless steels — mixed austenitic-ferritic microstructure, higher strength than austenitic grades, excellent corrosion resistance, require controlled heat input to maintain the correct phase balance." },
    { title: "Advanced Metallurgy — Aluminum", body: "Aluminum alloys — know the 4-digit designation system: 1XXX = pure aluminum, 2XXX = aluminum-copper (heat treatable, high strength), 3XXX = aluminum-manganese, 4XXX = aluminum-silicon (filler metals), 5XXX = aluminum-magnesium (strongest non-heat-treatable alloys, best for welding), 6XXX = aluminum-magnesium-silicon (heat treatable, common structural alloy), 7XXX = aluminum-zinc (highest strength, poor weldability). Oxide layer — aluminum forms a tenacious oxide layer that melts at 2050°C versus the base metal at approximately 660°C. The oxide must be removed before welding — mechanical removal or with the AC arc cleaning action in GTAW. Hot cracking in aluminum — aluminum alloys are susceptible to hot cracking (solidification cracking) depending on their composition. Filler metal selection is critical — choose a filler that shifts the weld metal composition away from the crack-susceptible range." },
    { title: "SAW — Submerged Arc Welding", body: "SAW uses a continuously fed solid wire electrode and the arc is completely submerged under a layer of granular flux — no visible arc, no UV radiation. High deposition rate and deep penetration make SAW the process of choice for welding thick plate in the flat position, including pressure vessel shells, structural sections, and ship hulls. Flux types — fused and agglomerated fluxes, flux classification, and the importance of dry storage (moisture in the flux causes porosity and hydrogen cracking in the same way as a wet SMAW electrode). Wire classification — EM12K is a common SAW wire, know the classification system. Parameters — SAW uses much higher currents than other processes (600–1000A is common) and the process produces wide, deeply penetrating welds. Multiple wire SAW — tandem and twin wire configurations for maximum deposition rate." },
    { title: "Pressure Vessel Code — ASME Section VIII Division 1", body: "ASME BPVC Section VIII Division 1 governs the design, fabrication, inspection, and testing of pressure vessels. For welders, the key knowledge areas are: Welding procedure qualification under ASME Section IX — the Welding Procedure Specification (WPS) and Procedure Qualification Record (PQR). Know the essential variables that, if changed, require re-qualification of the procedure (base metal P-number, filler metal F-number, significant changes in preheat, PWHT, and joint design). Welder performance qualification — how a welder qualifies to weld a specific procedure, what positions they are qualified for, and the period of effectiveness of their qualification. Code stamping — the CRN (Canadian Registration Number) system for pressure equipment in Canada and how it interfaces with ASME code requirements." },
    { title: "Pressure Piping Codes", body: "CSA Z662 — Canadian standard for oil and gas pipeline systems. Welding qualification requirements, NDE requirements for different pipeline service, and the specific requirements for pipeline girth welds. B31.3 Process Piping — welding requirements for industrial process plant piping. Know how the examination category (normal, Category D, Category M) affects NDE requirements. API 1104 — welding standard for pipelines, commonly required for pipeline welders. Know the qualification test requirements and what constitutes an acceptable test weld under API 1104." },
    { title: "Non-Destructive Examination — Understanding What Each Method Finds", body: "NDE is used to inspect welds without destroying them. Know the five major methods: Visual Testing (VT) — the most basic and first method applied. Know what visual inspection can and cannot detect. Liquid Penetrant Testing (PT) — a penetrant is applied to the surface, allowed to dwell, removed, and a developer applied to draw penetrant out of discontinuities. Detects surface-breaking defects only. Not effective on porous materials. Magnetic Particle Testing (MT) — a magnetic field is applied to the part and iron particles are applied. Particles concentrate at magnetic flux leakage points caused by discontinuities. Detects surface and near-surface defects in ferromagnetic materials only (not applicable to austenitic stainless or aluminum). Radiographic Testing (RT) — X-rays or gamma rays pass through the weld and expose a film or digital detector. Subsurface volumetric defects (porosity, inclusions, incomplete fusion) are detected. RT requires radiation safety precautions and is a slow, expensive method but provides a permanent record. Ultrasonic Testing (UT) — high-frequency sound waves are introduced into the weld and reflections from discontinuities are detected. Detects subsurface defects, faster than RT, and provides sizing capability. Phased array UT is increasingly replacing conventional UT and RT." },
    { title: "Welding Procedure Specifications", body: "A WPS is the document that specifies all the welding variables for a production weld — base metal, filler metal, joint design, preheat, interpass temperature, PWHT, shielding gas, and welding parameters. Know every section of a WPS and what it tells you. Essential variables versus non-essential variables — essential variables are those that affect the mechanical properties of the weld and require re-qualification if changed. Non-essential variables can be changed with a simple revision to the WPS without re-qualification. Pre-qualified WPS versus a qualified WPS — under AWS D1.1 Structural Welding Code, pre-qualified joint designs and consumable combinations can be used without testing; under ASME, all procedures must be qualified by testing." },
  ],
  catchOffGuardHeading: 'What Year 3 Welders Must Prepare for Most Carefully',
  catchOffGuard: [
    "Stainless steel sensitization — this is the most important and most tested stainless steel metallurgy topic. Know what it is, why it occurs, the sensitization temperature range, and all four prevention methods. An exam question on sensitization can be answered correctly in many different ways — understanding the mechanism ensures you can answer regardless of how the question is phrased.",
    "Welding procedure qualification under ASME Section IX — know the difference between a WPS and a PQR, know the essential variables, and know the welder qualification system. This content has significant exam representation and requires systematic study.",
    "NDE method selection — know not just what each method detects but what it cannot detect and what material or surface conditions are required. Exam questions often test the limits and requirements of each method, not just the general capability.",
  ],
  howToUseHeading: 'How to Use TradeBenchPrep for Year 3',
  howToUse: ["Full Exam Mode is the most important preparation tool for Year 3 — the final period exam draws from the complete three-year curriculum and is the most comprehensive exam of the apprenticeship. Run multiple full exams in your final two to three weeks. Study Mode for stainless and aluminum metallurgy, WPS qualification, and NDE method selection ensures complete coverage of Year 3-specific content. Use your dashboard to identify and address weak areas systematically in the time you have before your exam."],
});
